#!/bin/sh

if ! command -v brew ; then
    # Unattended Brew install
    echo | /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
    PATH=$PATH:/home/linuxbrew/.linuxbrew/bin
fi

# Ignore failure caused by Darwin-only dependencies
brew bundle --file=~/.Brewfile || true

./